<?xml version="1.0" standalone="yes"?>
<!DOCTYPE doc PUBLIC "-//UC Berkeley//DTD DocML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/DocML_1.dtd">
<doc name="ExceptionManager" class="ptolemy.actor.lib.ExceptionManager">
  <description>
The ExceptionManager catches exceptions and attempts to handle them with the&#10; specified policy.  It notifies ExceptionSubscribers after an exception has&#10; occurred and again after the handling attempt.  If the exception cannot be&#10; handled, the model Manager is informed.  </description>
  <author>Elizabeth Latronico</author>
  <version>$Id$</version>
  <since>Ptolemy II 10.0</since>
  <Pt.ProposedRating>Red (beth)</Pt.ProposedRating>
  <Pt.AcceptedRating>Red (beth)</Pt.AcceptedRating>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="exceptionMessage">The exception message from the caught exception.</property>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="policy">The error handling policy to apply if an exception occurs.&#10;  One of: restart, stop, throw.  See &lt;a href=&quot;../../../ptolemy/actor/lib/CatchExceptionAttribute.xml&quot;&gt;ptolemy.actor.lib.CatchExceptionAttribute&lt;/a&gt;</property>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="statusMessage">The latest action, if any, taken by the CatchExceptionAttribute.&#10;  For example, a notification that the model has restarted.&#10;  It offers a way to provide feedback to the user.</property>
</doc>
