<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
    <head>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Unit Test Results: All Failures</title>
        <link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
    </head>
    <body onload="open('allclasses-frame.html','classListFrame')">
        <h1>Unit Test Results.</h1>
        <table width="100%">
            <tr>
                <td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
            </tr>
        </table>
        <hr size="1">
        <h2>All Failures</h2>
        <table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
            <tr valign="top">
                <th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
            </tr>
            <tr valign="top" class="Failure">
                <td><a href="adm/installers/test/junit/0_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[0] /home/travis/build/icyphy/ptII/adm/installers/test/NightlyUpdate.tcl (RunTclFile)"></a><a href="adm/installers/test/junit/0_JUnitTclTest.html#[0] /home/travis/build/icyphy/ptII/adm/installers/test/NightlyUpdate.tcl (RunTclFile)">[0] /home/travis/build/icyphy/ptII/adm/installers/test/NightlyUpdate.tcl (RunTclFile)</a></td><td>Failure</td><td>Number of failed tests is has increased. expected:&lt;0&gt; but was:&lt;1&gt;
                    <br>
                    <br>
                    <code>junit.framework.AssertionFailedError: Number of failed tests is has increased. expected:&lt;0&gt; but was:&lt;1&gt;
                        <br>
                        	at ptolemy.util.test.junit.TclTests.RunTclFile(TclTests.java:286)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
                        <br>
                        	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
                        <br>
                    </code></td><td>53.978</td>
            </tr>
            <tr valign="top" class="Failure">
                <td><a href="ptolemy/vergil/basic/export/test/junit/190_ExportModelJUnitTestBatch6.html">ExportModelJUnitTestBatch6</a></td><td><a name="[95] ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml (RunExportModel)"></a><a href="ptolemy/vergil/basic/export/test/junit/190_ExportModelJUnitTestBatch6.html#[95] ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml (RunExportModel)">[95] ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml (RunExportModel)</a></td><td>Failure</td><td>Exporting HTML for ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml failed: 
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at ptolemy.vergil.basic.export.ExportModel.exportModel(ExportModel.java:401)
	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:153)
	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1182)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1033)
Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
  in .DOPCenter.DatabaseManager
Because:
Communications link failure

Last packet sent to the server was 0 ms ago.
	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:397)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
  in .DOPCenter.DatabaseManager
Because:
Communications link failure

Last packet sent to the server was 0 ms ago.
	at ptolemy.actor.lib.database.DatabaseManager.getConnection(DatabaseManager.java:566)
	at ptolemy.actor.lib.database.DatabaseManager.preinitialize(DatabaseManager.java:583)
	at ptolemy.actor.Director.preinitialize(Director.java:1302)
	at ptolemy.actor.Director.preinitialize(Director.java:1257)
	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:763)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1828)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:390)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ptolemy.actor.lib.database.DatabaseManager$MakeConnection.run(DatabaseManager.java:633)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:436)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:246)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
	... 12 more

                    <br>
                    <br>
                    <code>junit.framework.AssertionFailedError: Exporting HTML for ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml failed: 
                        <br>
                        java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
                        <br>
                        	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
                        <br>
                        	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel.exportModel(ExportModel.java:401)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:153)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
                        <br>
                        	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
                        <br>
                        	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
                        <br>
                        Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
                        <br>
                          in .DOPCenter.DatabaseManager
                        <br>
                        Because:
                        <br>
                        Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:397)
                        <br>
                        	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
                        <br>
                        	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
                        <br>
                        	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
                        <br>
                        	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
                        <br>
                        	at java.base/java.security.AccessController.doPrivileged(Native Method)
                        <br>
                        	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
                        <br>
                        	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
                        <br>
                          in .DOPCenter.DatabaseManager
                        <br>
                        Because:
                        <br>
                        Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager.getConnection(DatabaseManager.java:566)
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager.preinitialize(DatabaseManager.java:583)
                        <br>
                        	at ptolemy.actor.Director.preinitialize(Director.java:1302)
                        <br>
                        	at ptolemy.actor.Director.preinitialize(Director.java:1257)
                        <br>
                        	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:763)
                        <br>
                        	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1828)
                        <br>
                        	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
                        <br>
                        	at ptolemy.actor.Manager.initialize(Manager.java:710)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:356)
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:390)
                        <br>
                        Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
                        <br>
                        	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:718)
                        <br>
                        	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
                        <br>
                        	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
                        <br>
                        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
                        <br>
                        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager$MakeConnection.run(DatabaseManager.java:633)
                        <br>
                        Caused by: java.net.ConnectException: Connection refused (Connection refused)
                        <br>
                        	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
                        <br>
                        	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
                        <br>
                        	at java.base/java.net.Socket.connect(Socket.java:591)
                        <br>
                        	at java.base/java.net.Socket.connect(Socket.java:540)
                        <br>
                        	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:436)
                        <br>
                        	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:246)
                        <br>
                        	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
                        <br>
                        	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:280)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
                        <br>
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:162)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
                        <br>
                        	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
                        <br>
                        	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
                        <br>
                    </code></td><td>1.676</td>
            </tr>
            <tr valign="top" class="Failure">
                <td><a href="ptolemy/vergil/basic/export/test/junit/190_ExportModelJUnitTestBatch6.html">ExportModelJUnitTestBatch6</a></td><td><a name="[96] ptolemy/domains/space/demo/DOPCenter/Placard.xml (RunExportModel)"></a><a href="ptolemy/vergil/basic/export/test/junit/190_ExportModelJUnitTestBatch6.html#[96] ptolemy/domains/space/demo/DOPCenter/Placard.xml (RunExportModel)">[96] ptolemy/domains/space/demo/DOPCenter/Placard.xml (RunExportModel)</a></td><td>Failure</td><td>Exporting HTML for ptolemy/domains/space/demo/DOPCenter/Placard.xml failed: 
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at ptolemy.vergil.basic.export.ExportModel.exportModel(ExportModel.java:401)
	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:153)
	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1182)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1033)
Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
  in .Placard.DatabaseManager
Because:
Communications link failure

Last packet sent to the server was 0 ms ago.
	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:397)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
  in .Placard.DatabaseManager
Because:
Communications link failure

Last packet sent to the server was 0 ms ago.
	at ptolemy.actor.lib.database.DatabaseManager.getConnection(DatabaseManager.java:566)
	at ptolemy.actor.lib.database.DatabaseManager.preinitialize(DatabaseManager.java:583)
	at ptolemy.actor.Director.preinitialize(Director.java:1302)
	at ptolemy.actor.Director.preinitialize(Director.java:1257)
	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:763)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1828)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:390)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ptolemy.actor.lib.database.DatabaseManager$MakeConnection.run(DatabaseManager.java:633)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:436)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:246)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
	... 12 more

                    <br>
                    <br>
                    <code>junit.framework.AssertionFailedError: Exporting HTML for ptolemy/domains/space/demo/DOPCenter/Placard.xml failed: 
                        <br>
                        java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
                        <br>
                        	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
                        <br>
                        	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel.exportModel(ExportModel.java:401)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:153)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
                        <br>
                        	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
                        <br>
                        	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
                        <br>
                        Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
                        <br>
                          in .Placard.DatabaseManager
                        <br>
                        Because:
                        <br>
                        Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:397)
                        <br>
                        	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
                        <br>
                        	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
                        <br>
                        	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
                        <br>
                        	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
                        <br>
                        	at java.base/java.security.AccessController.doPrivileged(Native Method)
                        <br>
                        	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
                        <br>
                        	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                        <br>
                        	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Failed to open connection to the database.
                        <br>
                          in .Placard.DatabaseManager
                        <br>
                        Because:
                        <br>
                        Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager.getConnection(DatabaseManager.java:566)
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager.preinitialize(DatabaseManager.java:583)
                        <br>
                        	at ptolemy.actor.Director.preinitialize(Director.java:1302)
                        <br>
                        	at ptolemy.actor.Director.preinitialize(Director.java:1257)
                        <br>
                        	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:763)
                        <br>
                        	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1828)
                        <br>
                        	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
                        <br>
                        	at ptolemy.actor.Manager.initialize(Manager.java:710)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:356)
                        <br>
                        	at ptolemy.vergil.basic.export.ExportModel$2.run(ExportModel.java:390)
                        <br>
                        Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
                        <br>
                        <br>
                        Last packet sent to the server was 0 ms ago.
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
                        <br>
                        	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:718)
                        <br>
                        	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
                        <br>
                        	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
                        <br>
                        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
                        <br>
                        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
                        <br>
                        	at ptolemy.actor.lib.database.DatabaseManager$MakeConnection.run(DatabaseManager.java:633)
                        <br>
                        Caused by: java.net.ConnectException: Connection refused (Connection refused)
                        <br>
                        	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
                        <br>
                        	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
                        <br>
                        	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
                        <br>
                        	at java.base/java.net.Socket.connect(Socket.java:591)
                        <br>
                        	at java.base/java.net.Socket.connect(Socket.java:540)
                        <br>
                        	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:436)
                        <br>
                        	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:246)
                        <br>
                        	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
                        <br>
                        	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:280)
                        <br>
                        	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
                        <br>
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTest.RunExportModel(ExportModelJUnitTest.java:162)
                        <br>
                        	at ptolemy.vergil.basic.export.test.junit.ExportModelJUnitTestBatch.RunExportModel(ExportModelJUnitTestBatch.java:84)
                        <br>
                        	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
                        <br>
                        	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:41)
                        <br>
                        	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:237)
                        <br>
                        	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:215)
                        <br>
                    </code></td><td>1.500</td>
            </tr>
        </table>
    </body>
</html>
